### ISSUE TITLE
Visualizing Chunks of images stored as Dask Arrays 

### ISSUE THREAD

**Issue by martham93** [DigitalGlobe/gbdxtools#325] opened 2018-05-30 22:09 UTC
The method show in the [tutorial](https://notebooks.geobigdata.io/hub/notebooks/5a5e88930696557176a675c1?tab=code ) needs some modification for the code to work:  

The object in the tutorial "processed", the result of the method `map_blocks()` is a Dask Array that has ndvi values for chunks of images, but dask arrays no longer have an iterwindows method. 

Temporary workaround from @chelm: 
```from shapely.geometry import shape 
import matplotlib.pyplot as plt
%matplotlib inline

aoi = image.randwindow((500,500))
bounds = image.pxbounds(shape(aoi))

ndwi_aoi = processed[:, bounds[1]:bounds[3], bounds[0]:bounds[2]]

plt.axis('off')
plt.imshow(ndwi_aoi[0,:,:], cmap="jet")
plt.show()
```

**Comment by chelm** [comment] 2018-05-31 15:00
Here is some reproducable code

```python
from gbdxtools import CatalogImage
import numpy as np

image = CatalogImage('10400100137F4900')

def ndwi(chunk):
    return np.expand_dims(np.clip((chunk[4,:,:] - chunk[7,:,:]) / (chunk[4,:,:] + chunk[7,:,:]), -1, 1), axis=0)

processed = image.map_blocks(ndwi, dtype=image.dtype, chunks=(1,256,256))
aoi = processed.randwindow((500,500))
aoi.plot()
```

Results in `AttributeError: 'Array' object has no attribute 'randwindow'`

**Comment by rjpolackwich** [comment] 2018-05-31 15:37
Good catch in the tutorials, this raises a good point. Thanks for making an issue.

This functionality was originally removed [see here](https://github.com/DigitalGlobe/gbdxtools/commit/07cb1f18327727aa1904521785d62550bffdf4fc#diff-d59f5c40ea82272b74f7847f14987fee)  as part of a recent refactor that in large part aimed to   simplify the interface to creation and inheritance of our base dask classes both in functionality as well as code, and in particular for the reasons mentioned in the comments in the referenced commit.

Building `GeoDaskImage` around dask is important for two reasons: we get access to a large selection of the numpy array interface (adopted by dask), and we get execution control and optimization when using it.  `GeoDaskImage` is useful since it leverages both with our additional interface that let's us operate in a geospatial context, which is what makes it a great tool. Though to be powerful, we should be able to return a consistent interface (`GeoDaskImage` or derived) when we call a function that is relevant in the context of any geospatial operation, otherwise it's not really interesting in analytical contexts. 

So for sure we should be able to call `map_blocks` and return another geoimage. Can we do this without wrapping `__getattr__`?  A couple thoughts and related questions:

* Do people actually want to be able to use the array interface? If the answer were no, we could provide what's needed by implementing core common geospatial methods ourselves that use those things. Eg, we could write a `.ndvi` and `.iter_ndvi`, etc, or whatever and not worry about supporting dask-np array stuff, probably without a lot of issues from users I would guess. Frankly I think that kind of sucks because I want to do a lot of diff things in spatial and analytical contexts, and I want to be able to rely on staying geo-relevant when I do.

* Does it make sense to implement every function that returns an array as provided by dask in this context?  For instance, an element-wise, shape-preserving method like `map_blocks` should probably for sure return a geo instance, since these kinds of methods allow us to do things like band math, various convolutions etc that are core to geospatial operations. What about other methods that return arrays, but don't necessarily make sense in the context of geo? Eg, a function like `coarsen` reduces dimensionality. Would our interface still make sense (or work) when we fundamentally change the array in these kinds of ways?  

* We can't benefit from the usage of a metaclass here since dask.Array does that

* If we can answer that question, we could implement a support interface. That would mean we are tightly coupled to the exact dask array interface (which frankly we already are anyway) and would require a lil bit of new but important work. This option isn't so bad actually and is basically what dask has done to implement numpy - our paradigm is similar. This could be a mixin. Can still do the first bullet too.

* So, all of this implies another, imo pretty relevant question: what about in-memory geo-operations? I.e., should we be providing our interface to in-memory arrays (numpy) as well?  I really think we should, it's consistent with the part of our two-part goal to 1) provide an easy interface to working with very-large too-big-to-fit data and 2) provide geospatial context and interface. I think it would be really sweet to have this kind of thing. It could be a second part to the immediate work, and likely more involved, but would make gbdxtools even more powerful and consistent. It does seem like a doable thing as well.  

Those are my various thoughts and suggestions around this. What do you guys  @chelm @martham93 think about all this? Interested in any feedback. Maybe this is something you might be interested in helping out with @martham93 ? If so, I'd be happy to work with you, and could be a good way to get into working with and understanding gbdxtools.

**Comment by rjpolackwich** [comment] 2018-05-31 15:44
@drwelby welcome your ideas on this here too

**Comment by drwelby** [comment] 2018-05-31 17:36
I thought the point of `map_blocks` was to keep things in Dask and preserve the geospatial metadata. I noticed some of the notebooks convert the image to a numpy array and then do analysis on it, which makes a pretty picture but breaks the point of doing spatial analysis. But I think the example of `map_blocks` I saw generated a geotiff so there was no final computation to numpy array. It directly wrote each mapped chunk to the file.

Is the problem here that `.compute()` doesn't really do everything we want it to do, and we need something like `.geo_compute()`?

**Comment by chelm** [comment] 2018-05-31 18:04
@drwelby thats a bit of a different issue. The problem here is that `.map_blocks` returns a Dask Array, not a numpy array. Since the result is a dask.array and not one of our `GeoDaskImage` arrays we lose access to our spatial functions and other helps like `randwindow` and `rgb` and `plot` and others. 

Calling compute specifically ends the dask chain of ops and returns a numpy array. For now i think we should keep that in tact, though what @rjpolackwich brought up is worth thinking about: can we support our spatial and non-spatial methods on the result of compute. But i dont think we should conflate the 2 issues here.

**Comment by chelm** [comment] 2018-05-31 18:13
@rjpolackwich I think you're right, if i understand all that, in that what we have are two sets of work to do here. 

First, we should aim to support at least `.map_blocks` and maybe a few other dask methods by wrapping them via a mixin like you said. That get us past this initial issue. 

Second, i think it would be insanely powerful to support at least the spatial capabilities we add to dask arrays on post-computed numpy arrays. But lets handle that as a separate follow on issue. 

I'd rather see the immediate problems solved and then take on further enhancements.

**Comment by drwelby** [comment] 2018-05-31 19:55
@chelm I was thinking of this notebook:

https://notebooks.geobigdata.io/hub/notebooks/5a0f5d4439fa3411fa46d377?tab=code

where you run `.map_blocks` and then write out a geotiff, but I tried to run it and it is indeed broken.

**Comment by chelm** [comment] 2018-05-31 19:58
@drwelby right thats the one that started all this, i think the immediate need is for a little wrapper around map_blocks. Pre-refactor we were wrapping all the methods in dask.array so that this would work. But for reasons mentioned above it was a pretty nasty pattern esp. when using a notebook.

**Comment by rjpolackwich** [comment] 2018-06-01 13:19
Closing this for now (a [fix](https://github.com/DigitalGlobe/gbdxtools/commit/fc48f628df141c1ea73a7d7ac8db7bfbb08d59a9) was pushed to dev), but will open another ticket to support the larger scope of the work that needs to be done regarding this conversation

**Closed as completed by rjpolackwich** 2018-06-01 13:19 UTC
