### ISSUE TITLE
upgrading gbdxtools on windows, downgrade pycurl

### ISSUE THREAD

**Issue by joemcglinchy** [DigitalGlobe/gbdxtools#225] opened 2018-02-01 18:15 UTC
Hello, I was looking at upgrading gbdxtools to 0.14.3 since I saw that ACOMP has been enabled for CatalogImage. However, I noticed that it wants to downgrade pycurl to the version that was causing the issue in https://github.com/DigitalGlobe/gbdxtools/issues/223. here is the result of conda install -c digitalglobe gbdxtools

what do you suggest so as to avoid the PyCurl issue?

```
C:\Windows\System32>conda install -c digitalglobe gbdxtools
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment C:\Anaconda2\envs\joemcg_rootclone:

The following packages will be UPDATED:

    curl:          7.49.1-vc9_2      conda-forge [vc9] --> 7.55.1-vc9_0   conda-forge [vc9]
    expat:         2.1.0-vc9_3       conda-forge [vc9] --> 2.2.5-vc9_0    conda-forge [vc9]
    geotiff:       1.4.2-vc9_0       conda-forge [vc9] --> 1.4.2-vc9_1    conda-forge [vc9]
    h5py:          2.7.0-np111py27_0 conda-forge --> 2.7.1-py27_2   conda-forge
    hdf5:          1.8.17-vc9_11     conda-forge [vc9] --> 1.10.1-vc9_1   conda-forge [vc9]
    kealib:        1.4.6-vc9_3       conda-forge [vc9] --> 1.4.7-vc9_4    conda-forge [vc9]
    libgdal:       2.0.0-vc9_1                   --> 2.1.4-vc9_9    conda-forge [vc9]
    libnetcdf:     4.4.0-vc9_3       conda-forge [vc9] --> 4.4.1.1-vc9_10 conda-forge [vc9]
    libpng:        1.6.28-vc9_2      conda-forge [vc9] --> 1.6.34-vc9_0   conda-forge [vc9]
    libspatialite: 4.3.0a-vc9_18     conda-forge [vc9] --> 4.3.0a-vc9_19  conda-forge [vc9]
    libtiff:       4.0.7-vc9_1       conda-forge [vc9] --> 4.0.9-vc9_0    conda-forge [vc9]
    pytables:      3.4.2-np111py27_0 conda-forge --> 3.4.2-py27_7   conda-forge
    sqlite:        3.13.0-vc9_1      conda-forge [vc9] --> 3.20.1-vc9_2   conda-forge [vc9]

The following packages will be DOWNGRADED:

    freetype:      2.7-vc9_2         conda-forge [vc9] --> 2.7-vc9_1      conda-forge [vc9]
    pillow:        4.3.0-py27_1      conda-forge --> 4.2.1-py27_0   conda-forge
    pycurl:        7.43.0-py27_1                 --> 7.19.0-py27_0
```

**Comment by chelm** [comment] 2018-02-01 20:55
Whoa thats not good. Not sure what the cause of that would be. Let me research it

**Comment by chelm** [comment] 2018-02-01 21:06
This seems suspect... https://github.com/DigitalGlobe/gbdxtools/blob/master/environment.yml#L275

Might need a new release to fix this.

**Comment by chelm** [comment] 2018-02-01 21:15
@joemcglinchy I'm not getting the downgrade for some reason, but can you try to install in clean conda env: `conda create -n gbdxtool.14.3 -c digitalglobe gbdxtools` ?

**Comment by joemcglinchy** [comment] 2018-02-01 21:19
here is the output of that... no call for pycurl 7.19.0

```
conda create -n gbdxtool.14.3 -c digitalglobe gbdxtools
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment C:\Anaconda2\envs\gbdxtool.14.3:

The following NEW packages will be INSTALLED:

    affine:                        2.1.0-py_1          conda-forge
    asn1crypto:                    0.22.0-py27_0       conda-forge
    backports:                     1.0-py27_1          conda-forge
    backports.functools_lru_cache: 1.4-py27_1          conda-forge
    backports_abc:                 0.5-py27_0          conda-forge
    blinker:                       1.4-pyh2ce36e6_0    digitalglobe
    bokeh:                         0.12.13-py27_0      conda-forge
    boto:                          2.48.0-py27_0
    ca-certificates:               2017.11.5-0         conda-forge
    cachetools:                    2.0.1-pyh76454e0_0  digitalglobe
    certifi:                       2017.11.5-py27_0    conda-forge
    cffi:                          1.11.2-py27_0       conda-forge
    chardet:                       3.0.4-py27_0        conda-forge
    click:                         6.7-py_1            conda-forge
    cloudpickle:                   0.5.2-py_0          conda-forge
    configparser:                  3.5.0-pyhc3b37fc_0  digitalglobe
    cryptography:                  2.1.4-py27_0        conda-forge
    curl:                          7.49.1-vc9_2        conda-forge  [vc9]
    cycler:                        0.10.0-py27_0       conda-forge
    dask:                          0.16.1-py_0         conda-forge
    dask-core:                     0.16.1-py_0         conda-forge
    decorator:                     4.1.2-py27_0        conda-forge
    distributed:                   1.20.2-py27_0       conda-forge
    enum34:                        1.1.6-py27_1        conda-forge
    ephem:                         3.7.6.0-py27_1      conda-forge
    freetype:                      2.8.1-vc9_0         conda-forge  [vc9]
    functools32:                   3.2.3.2-py27_1      conda-forge
    future:                        0.16.0-py27_0       conda-forge
    futures:                       3.2.0-py27_0        conda-forge
    gbdx-auth:                     0.2.4-pyh3b05649_0  digitalglobe
    gbdxtools:                     0.14.3-pyhb38e0d4_0 digitalglobe
    geos:                          3.6.2-vc9_1         conda-forge  [vc9]
    heapdict:                      1.0.0-py27_0        conda-forge
    icu:                           58.2-vc9_0          conda-forge  [vc9]
    idna:                          2.6-py27_1          conda-forge
    imageio:                       2.2.0-py27_0        conda-forge
    ipaddress:                     1.0.18-py27_0       conda-forge
    jinja2:                        2.10-py27_0         conda-forge
    jpeg:                          9b-vc9_2            conda-forge  [vc9]
    libpng:                        1.6.34-vc9_0        conda-forge  [vc9]
    libtiff:                       4.0.9-vc9_0         conda-forge  [vc9]
    locket:                        0.2.0-py27_1        conda-forge
    markupsafe:                    1.0-py27_0          conda-forge
    matplotlib:                    2.1.2-py27_0        conda-forge
    mercantile:                    0.10.0-pyh6f6f923_0 digitalglobe
    mkl:                           2017.0.3-0
    msgpack-python:                0.5.1-py27_0        conda-forge
    networkx:                      2.0-py27_1          conda-forge
    numpy:                         1.13.1-py27_0
    oauthlib:                      2.0.2-py27_0        digitalglobe
    olefile:                       0.44-py27_0         conda-forge
    openssl:                       1.0.2n-vc9_0        conda-forge  [vc9]
    pandas:                        0.22.0-py27_0       conda-forge
    partd:                         0.3.8-py27_0        conda-forge
    pillow:                        5.0.0-py27_0        conda-forge
    pip:                           9.0.1-py27_1        conda-forge
    psutil:                        5.4.0-py27_0        conda-forge
    pycparser:                     2.18-py27_0         conda-forge
    pycurl:                        7.43.0-py27_1
    pyjwt:                         1.5.3-pyhfecc4d4_0  digitalglobe
    pyopenssl:                     17.2.0-py27_0       conda-forge
    pyparsing:                     2.2.0-py27_0        conda-forge
    pyproj:                        1.9.5.1-py27_0      conda-forge
    pyqt:                          5.6.0-py27_4        conda-forge
    pysocks:                       1.6.8-py27_1        conda-forge
    python:                        2.7.14-4            conda-forge
    python-dateutil:               2.6.1-py27_0        conda-forge
    pytz:                          2017.3-py_2         conda-forge
    pywavelets:                    0.5.2-py27_1        conda-forge
    pyyaml:                        3.12-py27_1         conda-forge
    qt:                            5.6.2-vc9_1         conda-forge  [vc9]
    requests:                      2.18.4-py27_1       conda-forge
    requests-futures:              0.9.7-pyh7d928a9_0  digitalglobe
    requests-oauthlib:             0.8.0-pyh9f1da8d_0  digitalglobe
    scikit-image:                  0.13.0-py27_2       conda-forge
    scipy:                         0.19.1-np113py27_0
    setuptools:                    38.4.0-py27_0       conda-forge
    shapely:                       1.6.4-py27_0        conda-forge
    singledispatch:                3.4.0.3-py27_0      conda-forge
    sip:                           4.18-py27_1         conda-forge
    six:                           1.11.0-py27_1       conda-forge
    sortedcontainers:              1.5.7-py27_0        conda-forge
    ssl_match_hostname:            3.5.0.1-py27_1      conda-forge
    tblib:                         1.3.2-py27_0        conda-forge
    toolz:                         0.8.2-py_2          conda-forge
    tornado:                       4.5.3-py27_0        conda-forge
    urllib3:                       1.22-py27_0         conda-forge
    vc:                            9-0                 conda-forge
    vs2008_runtime:                9.0.30729.6161-0    conda-forge
    wheel:                         0.30.0-py27_2       conda-forge
    win_inet_pton:                 1.0.1-py27_1        conda-forge
    wincertstore:                  0.2-py27_0          conda-forge
    yaml:                          0.1.7-vc9_0         conda-forge  [vc9]
    zict:                          0.1.3-py_0          conda-forge
    zlib:                          1.2.11-vc9_0        conda-forge  [vc9]
```

**Comment by chelm** [comment] 2018-02-01 21:29
Ok so i'm not convinced it's purely gbdxtools as it installed the proper pycurl version, but could be related to either a previous package in the other env or something. 

Maybe try to add --verbose to the original install and see if it tells us what package wants it to be downgraded.

**Comment by chelm** [comment] 2018-02-01 21:39
oh also can you `conda list` the first env? Maybe that can shed light

**Comment by joemcglinchy** [comment] 2018-02-01 21:58
here is the result for --verbose, I don't see much in there:

```
conda install -c digitalglobe gbdxtools --verbose
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment C:\Anaconda2\envs\joemcg_rootclone:

The following packages will be UPDATED:

    curl:          7.49.1-vc9_2      conda-forge [vc9] --> 7.55.1-vc9_0   conda-forge [vc9]
    expat:         2.1.0-vc9_3       conda-forge [vc9] --> 2.2.5-vc9_0    conda-forge [vc9]
    geotiff:       1.4.2-vc9_0       conda-forge [vc9] --> 1.4.2-vc9_1    conda-forge [vc9]
    h5py:          2.7.0-np111py27_0 conda-forge --> 2.7.1-py27_2   conda-forge
    hdf5:          1.8.17-vc9_11     conda-forge [vc9] --> 1.10.1-vc9_1   conda-forge [vc9]
    kealib:        1.4.6-vc9_3       conda-forge [vc9] --> 1.4.7-vc9_4    conda-forge [vc9]
    libgdal:       2.0.0-vc9_1                   --> 2.1.4-vc9_9    conda-forge [vc9]
    libnetcdf:     4.4.0-vc9_3       conda-forge [vc9] --> 4.4.1.1-vc9_10 conda-forge [vc9]
    libpng:        1.6.28-vc9_2      conda-forge [vc9] --> 1.6.34-vc9_0   conda-forge [vc9]
    libspatialite: 4.3.0a-vc9_18     conda-forge [vc9] --> 4.3.0a-vc9_19  conda-forge [vc9]
    libtiff:       4.0.7-vc9_1       conda-forge [vc9] --> 4.0.9-vc9_0    conda-forge [vc9]
    pytables:      3.4.2-np111py27_0 conda-forge --> 3.4.2-py27_7   conda-forge
    sqlite:        3.13.0-vc9_1      conda-forge [vc9] --> 3.20.1-vc9_2   conda-forge [vc9]

The following packages will be DOWNGRADED:

    freetype:      2.7-vc9_2         conda-forge [vc9] --> 2.7-vc9_1      conda-forge [vc9]
    pillow:        4.3.0-py27_1      conda-forge --> 4.2.1-py27_0   conda-forge
    pycurl:        7.43.0-py27_1                 --> 7.19.0-py27_0
```

Also, here is the result of ```conda list``` for the environment.. it is lengthy!

```
conda list
# packages in environment at C:\Anaconda2\envs\joemcg_rootclone:
#
_nb_ext_conf              0.2.0                    py27_0
affine                    2.1.0                      py_1    conda-forge
affine                    2.1.0                     <pip>
alabaster                 0.7.8                    py27_0
anaconda                  custom                   py27_0
anaconda-client           1.4.0                    py27_0
anaconda-navigator        1.2.1                    py27_0
apptools                  4.2.1                    py27_0
argcomplete               1.0.0                    py27_1
argcomplete               1.9.2                     <pip>
astroid                   1.4.9                    py27_0
astropy                   1.2.1               np111py27_0
attrs                     17.4.0                    <pip>
awscli                    1.11.136                  <pip>
babel                     2.3.3                    py27_0
backports                 1.0                      py27_0    conda-forge
backports.functools_lru_cache 1.4                      py27_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.4                      py27_0    conda-forge
beautifulsoup4            4.4.1                    py27_0
bitarray                  0.8.1                    py27_1
blaze                     0.10.1                   py27_0
blessings                 1.6                       <pip>
blinker                   1.4                pyh2ce36e6_0    digitalglobe
bokeh                     0.12.0                   py27_0
boto                      2.48.0                    <pip>
boto                      2.48.0                   py27_0
botocore                  1.6.3                     <pip>
bottleneck                1.1.0               np111py27_0    conda-forge
bumpversion               0.5.3                     <pip>
bzip2                     1.0.6                     vc9_1  [vc9]  conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
cachetools                2.0.1                     <pip>
cachetools                2.0.1              pyh76454e0_0    digitalglobe
cdecimal                  2.3                      py27_2
certifi                   2017.7.27.1               <pip>
certifi                   2017.11.5                py27_0    conda-forge
cffi                      1.6.0                    py27_0
chardet                   3.0.3                    py27_0
chardet                   3.0.4                     <pip>
chest                     0.2.3                    py27_0    conda-forge
click                     6.7                       <pip>
click                     6.6                      py27_0    conda-forge
click-plugins             1.0.3                     <pip>
click-plugins             1.0.3                    py27_0    conda-forge
cligj                     0.2.0                    py27_0
cloudpickle               0.4.0                    py27_0    conda-forge
cloudpickle               0.4.1                     <pip>
clyent                    1.2.2                    py27_0    conda-forge
colorama                  0.3.9                     <pip>
colorama                  0.3.7                    py27_0    conda-forge
comtypes                  1.1.2                    py27_0
configobj                 5.0.6                    py27_0
configparser              3.5.0                     <pip>
configparser              3.5.0b2                  py27_1
console_shortcut          0.1.1                    py27_1
contextlib2               0.5.3                    py27_0    conda-forge
contextlib2               0.5.5                     <pip>
crcmod                    1.7                       <pip>
cryptography              1.4                      py27_0
curl                      7.49.1                    vc9_2  [vc9]  conda-forge
cycler                    0.10.0                   py27_0    conda-forge
cython                    0.24                     py27_0    conda-forge
cytoolz                   0.8.0                    py27_0    conda-forge
dask                      0.16.0                     py_0    conda-forge
dask-core                 0.16.0                     py_0    conda-forge
datashape                 0.5.2                    py27_0
decorator                 4.0.10                   py27_0    conda-forge
decorator                 4.1.2                     <pip>
descartes                 1.1.0                    py27_0    conda-forge
dill                      0.2.5                    py27_0    conda-forge
distributed               1.20.2                   py27_0    conda-forge
docutils                  0.12                     py27_2
entrypoints               0.2.2                    py27_0    conda-forge
enum34                    1.1.6                    py27_0    conda-forge
envisage                  4.4.0                    py27_1
ephem                     3.7.6.0                   <pip>
ephem                     3.7.6.0                  py27_1    conda-forge
et_xmlfile                1.0.1                    py27_0    conda-forge
ExifRead                  2.1.2                     <pip>
expat                     2.1.0                     vc9_3  [vc9]  conda-forge
fastcache                 1.0.2                    py27_1
Fiona                     1.7.11                    <pip>
flask                     0.11.1                   py27_0    conda-forge
flask-cors                2.1.2                    py27_0
freetype                  2.7                       vc9_2  [vc9]  conda-forge
freexl                    1.0.4                     vc9_0  [vc9]  conda-forge
funcsigs                  1.0.2                    py27_0    conda-forge
functools32               3.2.3.2                  py27_0    conda-forge
future                    0.16.0                   py27_0    conda-forge
future                    0.16.0                    <pip>
futures                   3.1.1                     <pip>
futures                   3.0.5                    py27_0    conda-forge
gbdx-auth                 0.2.4              pyh3b05649_0    digitalglobe
gbdxtools                 0.14.3             pyhb38e0d4_0    digitalglobe
gcs-oauth2-boto-plugin    1.14                      <pip>
GDAL                      2.2.3                     <pip>
geomet                    0.1.1                     <pip>
geopandas                 0.3.0                    py27_0    conda-forge
geos                      3.6.2                     vc9_1  [vc9]  conda-forge
geotiff                   1.4.2                     vc9_0  [vc9]  conda-forge
get_terminal_size         1.0.0                    py27_0
gevent                    1.1.1                    py27_0
google-apitools           0.5.3                     <pip>
greenlet                  0.4.10                   py27_0
grin                      1.2.1                    py27_3
gsutil                    4.27                      <pip>
h5py                      2.7.0               np111py27_0    conda-forge
hdf4                      4.2.13                    vc9_0  [vc9]  conda-forge
hdf5                      1.8.17                   vc9_11  [vc9]  conda-forge
heapdict                  1.0.0                    py27_1
httplib2                  0.10.3                    <pip>
idna                      2.6                       <pip>
idna                      2.1                      py27_0    conda-forge
imageio                   2.2.0                    py27_0    conda-forge
imagesize                 0.7.1                    py27_0    conda-forge
ipaddress                 1.0.16                   py27_0    conda-forge
ipykernel                 4.3.1                    py27_0
ipyparallel               6.0.2                     <pip>
ipython                   4.2.0                    py27_0    conda-forge
ipython_genutils          0.1.0                    py27_0    conda-forge
ipywidgets                4.1.1                    py27_0    conda-forge
isort                     4.2.9                    py27_0    conda-forge
itsdangerous              0.24                     py27_0
jdcal                     1.2                      py27_1
jedi                      0.9.0                    py27_1
jinja2                    2.8                      py27_1    conda-forge
jmespath                  0.9.3                     <pip>
jpeg                      9b                        vc9_2  [vc9]  conda-forge
jsonschema                2.5.1                    py27_0    conda-forge
jupyter                   1.0.0                    py27_3
jupyter_client            4.3.0                    py27_0    conda-forge
jupyter_console           4.1.1                    py27_0    conda-forge
jupyter_core              4.1.0                    py27_0    conda-forge
kealib                    1.4.6                     vc9_3  [vc9]  conda-forge
krb5                      1.14.2                    vc9_0  [vc9]  conda-forge
lazy-object-proxy         1.2.2                    py27_0    conda-forge
libgdal                   2.0.0                     vc9_1  [vc9]
libiconv                  1.15                      vc9_0  [vc9]  conda-forge
libnetcdf                 4.4.0                     vc9_3  [vc9]  conda-forge
libpng                    1.6.28                    vc9_2  [vc9]  conda-forge
libpq                     9.6.3                     vc9_0  [vc9]  conda-forge
libspatialindex           1.8.5                     vc9_1  [vc9]  conda-forge
libspatialite             4.3.0a                   vc9_18  [vc9]  conda-forge
libssh2                   1.8.0                     vc9_2  [vc9]  conda-forge
libtiff                   4.0.7                     vc9_1  [vc9]  conda-forge
libxml2                   2.9.3                     vc9_9  [vc9]  conda-forge
linecache2                1.0.0                     <pip>
llvmlite                  0.11.0                   py27_0
locket                    0.2.0                    py27_1    conda-forge
lxml                      3.6.0                    py27_0
marionette-driver         2.2.0                     <pip>
markupsafe                0.23                     py27_2
matplotlib                1.5.1               np111py27_0
mayavi                    4.5.0                py27_vc9_3  [vc9]  conda-forge
mccabe                    0.6.1                    py27_0    conda-forge
menuinst                  1.4.1                    py27_0
mercantile                0.11.0                    <pip>
mercantile                0.10.0             pyh6f6f923_0    digitalglobe
metpy                     0.4.2                    py27_0    conda-forge
mistune                   0.7.2                    py27_0    conda-forge
mkl                       11.3.3                        1
mkl-service               1.1.2                    py27_2
mock                      2.0.0                     <pip>
mozdevice                 0.50                      <pip>
mozfile                   1.2                       <pip>
mozinfo                   0.9                       <pip>
mozlog                    3.4                       <pip>
moznetwork                0.27                      <pip>
mozprocess                0.25                      <pip>
mozprofile                0.28                      <pip>
mozrunner                 6.13                      <pip>
mozversion                1.4                       <pip>
mpmath                    0.19                     py27_1    conda-forge
msgpack-python            0.4.8                    py27_0    conda-forge
multipledispatch          0.4.8                    py27_0    conda-forge
munch                     2.2.0                    py27_0    conda-forge
natgrid                   0.2.1                     <pip>
nb_anacondacloud          1.1.0                    py27_0    conda-forge
nb_conda                  1.1.0                    py27_0
nb_conda_kernels          1.0.3                    py27_0    conda-forge
nbconvert                 4.2.0                    py27_0    conda-forge
nbformat                  4.0.1                    py27_0    conda-forge
nbformat                  4.4.0                     <pip>
nbpresent                 3.0.2                    py27_0    conda-forge
ndg-httpsclient           0.4.2                     <pip>
networkx                  2.0                       <pip>
networkx                  1.11                     py27_0    conda-forge
nltk                      3.2.1                    py27_0    conda-forge
nose                      1.3.7                    py27_1    conda-forge
notebook                  4.2.1                    py27_0    conda-forge
numba                     0.26.0              np111py27_0
numexpr                   2.6.1               np111py27_0    conda-forge
numpy                     1.11.1                   py27_1
numpy                     1.13.3                    <pip>
numpydoc                  0.6.0                    py27_0    conda-forge
oauth2client              2.2.0                     <pip>
oauthlib                  2.0.2                     <pip>
oauthlib                  2.0.2                    py27_0    conda-forge
odo                       0.5.0                    py27_1
olefile                   0.44                     py27_0    conda-forge
olefile                   0.44                      <pip>
openjpeg                  2.1.2                     vc9_3  [vc9]  conda-forge
openpyxl                  2.3.2                    py27_0
openssl                   1.0.2h                    vc9_0  [vc9]  conda-forge
pandas                    0.21.1                   py27_0    conda-forge
partd                     0.3.8                    py27_0    conda-forge
path.py                   8.2.1                    py27_0    conda-forge
pathlib2                  2.1.0                    py27_0    conda-forge
patsy                     0.4.1                    py27_0    conda-forge
pbr                       3.1.1                     <pip>
pcre                      8.39                      vc9_0  [vc9]  conda-forge
pep8                      1.7.0                    py27_0    conda-forge
pickleshare               0.7.2                    py27_0
pillow                    4.3.0                    py27_1    conda-forge
Pillow                    4.3.0                     <pip>
pint                      0.7.2                    py27_2    conda-forge
pip                       8.1.2                    py27_0    conda-forge
pip                       9.0.1                     <pip>
planet                    1.1.0                     <pip>
plotly                    2.0.15                    <pip>
ply                       3.8                      py27_0    conda-forge
proj4                     4.9.3                     vc9_5  [vc9]  conda-forge
psutil                    4.3.0                    py27_0    conda-forge
psycopg2                  2.7.3.2                  py27_0    conda-forge
py                        1.4.34                    <pip>
py                        1.4.31                   py27_0    conda-forge
pyasn1                    0.1.9                    py27_0    conda-forge
pyasn1-modules            0.0.11                    <pip>
pycosat                   0.6.1                    py27_1
pycparser                 2.14                     py27_1
pycrypto                  2.6.1                    py27_4
pycurl                    7.43.0                   py27_1
PyExifTool                0.1                       <pip>
pyface                    4.4.0                    py27_0
pyflakes                  1.2.3                    py27_0    conda-forge
pygeoif                   0.6                       <pip>
pygments                  2.1.3                    py27_0    conda-forge
PyJWT                     1.4.2                     <pip>
pyjwt                     1.5.3              pyhfecc4d4_0    digitalglobe
pylint                    1.6.4                    py27_1    conda-forge
pyopenssl                 16.2.0                   py27_0    conda-forge
pyparsing                 2.1.4                    py27_0
pyproj                    1.9.5.1                   <pip>
pyproj                    1.9.5.1                  py27_0    conda-forge
pyqt                      4.11.4                   py27_6
pyquery                   1.2.17                    <pip>
pyreadline                2.1                      py27_0    conda-forge
pysal                     1.14.3                   py27_0    conda-forge
pytables                  3.4.2               np111py27_0    conda-forge
pytest                    2.9.2                    py27_0    conda-forge
pytest                    3.2.3                     <pip>
pytest-runner             3.0                       <pip>
python                    2.7.12                        0
python-dateutil           2.5.3                    py27_0    conda-forge
python-gflags             3.1.1                     <pip>
pytz                      2016.4                   py27_0    conda-forge
PyWavelets                0.5.2                     <pip>
pywavelets                0.5.2               np111py27_0    conda-forge
pywin32                   220                      py27_1    conda-forge
PyYAML                    3.12                      <pip>
pyyaml                    3.11                     py27_4
pyzmq                     15.2.0                   py27_0
qt                        4.8.7                     vc9_6  [vc9]  conda-forge
qtawesome                 0.4.4                    py27_0    conda-forge
qtconsole                 4.2.1                    py27_0    conda-forge
qtpy                      1.2.1                    py27_0    conda-forge
rasterio                  1.0a12                    <pip>
requests                  2.14.2                   py27_0
requests                  2.18.4                    <pip>
requests-futures          0.9.7                     <pip>
requests-futures          0.9.7              pyh7d928a9_0    digitalglobe
requests-oauthlib         0.8.0                     <pip>
requests-oauthlib         0.8.0              pyh9f1da8d_0    digitalglobe
retry-decorator           1.1.0                     <pip>
rigidbody                 0.13                      <pip>
rope                      0.9.4                    py27_1
rsa                       3.4.2                     <pip>
rtree                     0.8.3                    py27_0    conda-forge
ruamel_yaml               0.11.14                  py27_0    conda-forge
s3transfer                0.1.10                    <pip>
scikit-image              0.13.0              np111py27_0    conda-forge
scikit-learn              0.17.1              np111py27_1
scipy                     0.18.0              np111py27_0
selenium                  3.4.3                     <pip>
setuptools                36.6.0                    <pip>
setuptools                23.0.0                   py27_0    conda-forge
shapely                   1.6.3                    py27_0    conda-forge
Shapely                   1.6.2.post1               <pip>
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0    conda-forge
sip                       4.16.9                   py27_2
six                       1.10.0                   py27_0    conda-forge
six                       1.11.0                    <pip>
snowballstemmer           1.2.1                    py27_0    conda-forge
snuggs                    1.4.1                     <pip>
sockjs-tornado            1.0.3                    py27_0
SocksiPy-branch           1.1                       <pip>
sortedcontainers          1.5.7                    py27_0    conda-forge
spectral                  0.19                      <pip>
sphinx                    1.4.1                    py27_0
sphinx_rtd_theme          0.1.9                    py27_0    conda-forge
splinter                  0.7.5                     <pip>
spyder                    3.1.4                    py27_0    conda-forge
sqlalchemy                1.0.13                   py27_0
sqlite                    3.13.0                    vc9_1  [vc9]  conda-forge
ssl_match_hostname        3.4.0.2                  py27_1
statsmodels               0.6.1               np111py27_1
sympy                     1.0                      py27_0    conda-forge
tbb                       2018_20170919             vc9_0  [vc9]  conda-forge
tblib                     1.3.2                    py27_0    conda-forge
tk                        8.5.19                    vc9_1  [vc9]  conda-forge
toolz                     0.8.0                    py27_0    conda-forge
toolz                     0.8.2                     <pip>
tornado                   4.5.2                    py27_0    conda-forge
tqdm                      4.14.0                    <pip>
traceback2                1.4.0                     <pip>
traitlets                 4.2.1                    py27_0    conda-forge
traits                    4.4.0                    py27_0
traitsui                  4.4.0                    py27_0
triangulation             0.12                      <pip>
unicodecsv                0.14.1                   py27_0    conda-forge
unittest2                 1.1.0                     <pip>
urllib3                   1.22                      <pip>
utm                       0.4.2                     <pip>
vc                        9                             0    conda-forge
vcrpy                     1.11.1                    <pip>
vs2008_runtime            9.00.30729.1                  2
vs2015_runtime            14.0.25420                    0    conda-forge
vtk                       7.1.1              py27_vc9_202  [vc9]  conda-forge
werkzeug                  0.11.10                  py27_0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
wrapt                     1.10.11                   <pip>
wrapt                     1.10.10                  py27_0
xerces-c                  3.2.0                     vc9_0  [vc9]  conda-forge
xlrd                      1.0.0                    py27_0    conda-forge
xlsxwriter                0.9.2                    py27_0
xlwings                   0.7.2                    py27_0
xlwt                      1.1.2                    py27_0
xz                        5.2.3                         0    conda-forge
yaml                      0.1.6                     vc9_0  [vc9]  conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                    vc9_0  [vc9]  conda-forge
```

**Comment by chelm** [comment] 2018-02-01 22:13
Dang im not sure at all whats up. another thing to try is to install gbdxtools, let conda downgrade pycurl and the install the latest pycurl and see if conda will complain.

**Comment by joemcglinchy** [comment] 2018-02-01 22:35
Last time I tried that there was something with installing pycurl at that version which caused it to mess up my gdal installation. I definitely don't want that to happen since I use rasterio/gdal within this same environment. I may consider going the route of a new environment.

**Comment by chelm** [comment] 2018-02-01 22:44
Yeah sounds good. Im hesitant to close this issue since we dont know the cause but i'm feeling like a clean install doesnt produce the issue and is the most probable solution

**Comment by chelm** [comment] 2018-02-02 16:49
Going to closes this as i cant seem to reproduce. If this is seen again I suggest trying a clean environment (or just reinstalling the latest version of pycurl)

**Closed as completed by chelm** 2018-02-02 16:49 UTC

**Comment by joemcglinchy** [comment] 2018-02-02 18:10
yep, all good! I can install rasterio and gdal wrom WHL files in a clean environment with no issue.

EDIT: not quite all good. This statement produces a logger error for shapely.geos (?):

```
>>> from gbdxtools import CatalogImage
>>> img = CatalogImage('104001002F595700')
No handlers could be found for logger "shapely.geos"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\envs\gbdxtool_updates\lib\site-packages\gbdxtools\images\catalog_image.py", line 36, in __new__
    return cls._image_by_type(cat_id, **kwargs)
  File "C:\Anaconda2\envs\gbdxtool_updates\lib\site-packages\gbdxtools\images\catalog_image.py", line 41, in _image_by_type
    aoi = wkt.dumps(box(-180, -90, 180, 90))
  File "C:\Anaconda2\envs\gbdxtool_updates\lib\site-packages\shapely\wkt.py", line 22, in dumps
    return geos.WKTWriter(geos.lgeos, trim=trim, **kw).write(ob)
  File "C:\Anaconda2\envs\gbdxtool_updates\lib\site-packages\shapely\geos.py", line 362, in write
    raise ValueError("Null geometry supports no operations")
ValueError: Null geometry supports no operations
```

**Comment by joemcglinchy** [comment] 2018-02-02 18:26
^^^ I am not sure why, but I tried the same command again and the image object was created without that error. I'm not sure why it happened the first time?  Odd! Thanks again for your help on this @chelm

**Comment by chelm** [comment] 2018-02-02 21:32
@joemcglinchy whoa yeah that's a funky one. Glad to know it went away. Users have reported some funky install things with shapely.
